[project]
name = "bilibili-live-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "asyncio>=4.0.0",
    "bilibili-api>=9.1.0",
    "configparser>=7.1.0",
    "prompt-toolkit>=3.0.51",
]
